# Generated by Django 5.1 on 2024-08-24 23:57

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('creci', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Creci')),
                ('Slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('CodEndereco', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Cep', models.CharField(max_length=8)),
                ('Numero', models.IntegerField()),
                ('Complemento', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('CodProprietario', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CodCliente', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('CodImovel', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('TipoImovel', models.CharField(max_length=15)),
                ('ValorImovel', models.FloatField()),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível?')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('CodVenda', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Data da venda', models.DateField()),
                ('Forma de pagamento', models.CharField(max_length=50)),
                ('Entrada', models.BooleanField(default=True)),
                ('Valor final', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Fotos', stdimage.models.StdImageField(force_min_size=False, upload_to='imoveis', variations={'thumb': (300, 300)})),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Intermedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('CodVisita', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('DataVisita', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visita')),
            ],
        ),
    ]
