# Generated by Django 5.1 on 2024-08-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('creci', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Creci')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('CodigoCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('CodigoImovel', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('proprietario', models.CharField(max_length=100, verbose_name='Proprietario')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
            ],
        ),
    ]
