# Generated by Django 5.1 on 2024-09-02 01:16

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('Nome', models.CharField(max_length=50)),
                ('Creci', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Ativo', models.BooleanField(default=True)),
                ('Slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('CodEndereco', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Rua', models.CharField(max_length=40)),
                ('Bairro', models.CharField(max_length=25)),
                ('Numero', models.IntegerField()),
                ('Cidade', models.CharField(max_length=30)),
                ('Complemento', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('CodProprietario', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('CodCliente', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=15)),
                ('Ativo', models.BooleanField(default=True)),
                ('Comprou', models.BooleanField(default=False)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('CodImovel', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('TipoImovel', models.CharField(max_length=15)),
                ('ValorImovel', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Disponivel', models.BooleanField(default=True)),
                ('Fotos', stdimage.models.StdImageField(force_min_size=False, upload_to='imoveis', variations={'thumb': (300, 300)})),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('CodVenda', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('Data da venda', models.DateField()),
                ('Forma de pagamento', models.CharField(max_length=50)),
                ('Entrada', models.BooleanField(default=True)),
                ('Valor final', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intermedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('CodVisita', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('DataVisita', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criação', models.DateField(auto_now_add=True)),
                ('Modificado', models.DateField(auto_now=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visita')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
