# Generated by Django 5.1 on 2024-09-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='Slug',
        ),
    ]
