# Generated by Django 5.1 on 2024-08-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='ValorImovel',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.imovel'),
        ),
    ]
