# Generated by Django 4.2.8 on 2023-12-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imovel_alter_cliente_contatoinicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('creci', models.IntegerField(verbose_name='Creci')),
            ],
        ),
    ]
