# Generated by Django 5.1.1 on 2024-10-21 14:05

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_corretor_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='Data da venda',
            new_name='DataVenda',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='Forma de pagamento',
            new_name='FormaPagamento',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='Valor final',
            new_name='ValorFinal',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='Complemento',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='Fotos',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': (300, 300)}),
        ),
    ]
