# Generated by Django 4.2.8 on 2023-12-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='corretor',
            field=models.CharField(default='Imobiliaria', max_length=50, verbose_name='Corretor'),
            preserve_default=False,
        ),
    ]
