# Generated by Django 5.1 on 2024-08-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_imovel_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='andamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contatoInicial',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dataEntrada',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dataUltimAtualiza',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='situacao',
        ),
        migrations.RemoveField(
            model_name='corretor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='midia',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='residencial',
        ),
        migrations.AddField(
            model_name='cliente',
            name='CodigoCliente',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='corretor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.corretor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='CodigoImovel',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Creci'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='corretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corretor'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.CharField(max_length=100, verbose_name='Proprietario'),
        ),
    ]
